org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
# This builtInKotlin flag was added by the Flutter template
kotlin.jvm.target.validation.mode=IGNORE

# IRIS MASTER14C deterministic Android build runtime

# IRIS MASTER14C deterministic Android build runtime

# IRIS MASTER14C deterministic Android build runtime

# IRIS MASTER14C-R2 deterministic Android build runtime
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
android.newDsl=false
android.builtInKotlin=false
